// #autogenerated
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TarokScoreBoard.Core.Entities
{
  [Table("game_player")]
  public partial class GamePlayer
  { 
    [Column("game_id")]
    public Guid GameId { get; set; }

    [Column("name")]
    public string Name { get; set; }

    [Column("player_id")]
    public Guid PlayerId { get; set; }
  }
}