// #autogenerated
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TarokScoreBoard.Core.Entities
{
  [Table("team_player")]
  public partial class TeamPlayer
  { 
    [Column("name")]
    public string Name { get; set; }

    [Column("player_id")]
    public Guid PlayerId { get; set; }

    [Column("team_id")]
    public Guid TeamId { get; set; }
  }
}