// #autogenerated
using Npgsql;
using Dapper;
using System.Threading.Tasks;
using System;
using TarokScoreBoard.Core.Entities;

namespace TarokScoreBoard.Infrastructure.Repositories
{
  public class TeamBaseRepository : BaseRepository<Team>
  {
    protected string selectFields = @"
        passphrase, 
				team_id, 
				team_name";

    protected override string BaseSelect { get; set; }

    public TeamBaseRepository(NpgsqlConnection conn) : base(conn)
    {    
      BaseSelect = $@"
        SELECT
          {selectFields}
        FROM team";
    }

    
    public Team Add(Team entity)
    {
      return conn.QueryFirst<Team>($@"
      INSERT INTO team
      (
        passphrase, 
				team_id, 
				team_name
      )
      VALUES (:Passphrase, :TeamId, :TeamName)
      RETURNING
        {selectFields}
      ",
      entity);
    }

    public async Task<Team> AddAsync(Team entity)
    {
      return await conn.QueryFirstAsync<Team>($@"
      INSERT INTO team
      (
        passphrase, 
				team_id, 
				team_name
      )
      VALUES (:Passphrase, :TeamId, :TeamName)
      RETURNING
        {selectFields}
      ",
      entity);
    }
  }
}
