// #autogenerated
using Npgsql;
using Dapper;
using System.Threading.Tasks;
using System;
using TarokScoreBoard.Core.Entities;

namespace TarokScoreBoard.Infrastructure.Repositories
{
  public class TeamPlayerBaseRepository : BaseRepository<TeamPlayer>
  {
    protected string selectFields = @"
        name, 
				player_id, 
				team_id";

    protected override string BaseSelect { get; set; }

    public TeamPlayerBaseRepository(NpgsqlConnection conn) : base(conn)
    {    
      BaseSelect = $@"
        SELECT
          {selectFields}
        FROM team_player";
    }

    
    public TeamPlayer Add(TeamPlayer entity)
    {
      return conn.QueryFirst<TeamPlayer>($@"
      INSERT INTO team_player
      (
        name, 
				player_id, 
				team_id
      )
      VALUES (:Name, :PlayerId, :TeamId)
      RETURNING
        {selectFields}
      ",
      entity);
    }

    public async Task<TeamPlayer> AddAsync(TeamPlayer entity)
    {
      return await conn.QueryFirstAsync<TeamPlayer>($@"
      INSERT INTO team_player
      (
        name, 
				player_id, 
				team_id
      )
      VALUES (:Name, :PlayerId, :TeamId)
      RETURNING
        {selectFields}
      ",
      entity);
    }
  }
}
